import { Property } from './types';

export const NATIONWIDE_VACANT_PROPERTIES: Property[] = [
  {
    id: 'prop-101',
    apn: '201-14-998A',
    county: 'Maricopa',
    state: 'AZ',
    city: 'Phoenix',
    acreage: 4.5,
    zoning: 'Agricultural (Light)',
    price: 32000,
    marketValue: 55000,
    ownerName: 'Dan Henderson',
    ownerPhone: '+1 (602) 555-1940',
    ownerMailAddress: '1440 Camelback Rd, Phoenix, AZ 85016',
    ownerPhysicalAddress: 'Subdivision Section 12, Phoenix, AZ 85001',
    leadScore: 92,
    status: 'Lead',
    roadAccess: true,
    utilitiesNearby: true,
    notes: 'Direct dirt road access with direct power pole tie-ins. Appraised highly by property office.',
    coords: { lat: 33.4484, lng: -112.0740 },
    appraiserRecordId: 'M-AZ-PHX-4491902'
  },
  {
    id: 'prop-102',
    apn: '110-04-982B',
    county: 'Costilla',
    state: 'CO',
    city: 'Fort Garland',
    acreage: 40.0,
    zoning: 'Residential (Rural)',
    price: 24000,
    marketValue: 49000,
    ownerName: 'Sarah Higgins',
    ownerPhone: '+1 (719) 555-4819',
    ownerMailAddress: '88 Blanca Vista Dr, Fort Garland, CO 81133',
    ownerPhysicalAddress: 'Wild Horse Mesa Sec 4, Fort Garland, CO 81133',
    leadScore: 84,
    status: 'Approved',
    roadAccess: false,
    utilitiesNearby: false,
    notes: 'Gorgeous high elevation off-grid meadow. Easement access verified from property plats.',
    coords: { lat: 37.2844, lng: -105.3921 },
    appraiserRecordId: 'C-CO-COS-1194812'
  },
  {
    id: 'prop-103',
    apn: '882-19-112C',
    county: 'Valencia',
    state: 'NM',
    city: 'Belen',
    acreage: 10.2,
    zoning: 'Agricultural/Ranch',
    price: 8500,
    marketValue: 21050,
    ownerName: 'Marcus Aurelius NM LLC',
    ownerPhone: '+1 (505) 555-8912',
    ownerMailAddress: '900 Via Roma Dr, Rome, GA 30161',
    ownerPhysicalAddress: 'El Cerro Loop Block B, Belen, NM 87002',
    leadScore: 96,
    status: 'Sold',
    roadAccess: true,
    utilitiesNearby: false,
    notes: 'Flat desert tract which is hot on our investor list. Zoned for modular builds of any size.',
    coords: { lat: 34.6617, lng: -106.7761 },
    appraiserRecordId: 'V-NM-VAL-8822019'
  },
  {
    id: 'prop-104',
    apn: '330-01-443D',
    county: 'Klamath',
    state: 'OR',
    city: 'Klamath Falls',
    acreage: 18.5,
    zoning: 'Forestry/Timber',
    price: 49000,
    marketValue: 98000,
    ownerName: 'Kellen Weaver',
    ownerPhone: '+1 (541) 555-2234',
    ownerMailAddress: '433 Pines Edge Ln, Klamath Falls, OR 97601',
    ownerPhysicalAddress: 'Lakeview Forest Tract 19, Klamath Falls, OR 97601',
    leadScore: 89,
    status: 'Lead',
    roadAccess: true,
    utilitiesNearby: true,
    notes: 'Heavily wooded. High-density residential conversion possible according to city appraiser records.',
    coords: { lat: 42.2249, lng: -121.7817 },
    appraiserRecordId: 'K-OR-KLM-9021200'
  },
  {
    id: 'prop-105',
    apn: '557-04-331E',
    county: 'Elko',
    state: 'NV',
    city: 'Elko',
    acreage: 20.0,
    zoning: 'Open Range',
    price: 15000,
    marketValue: 31000,
    ownerName: 'Elena Rostova',
    ownerPhone: '+1 (775) 555-9011',
    ownerMailAddress: '12 St. Petersburg Ave, Las Vegas, NV 89109',
    ownerPhysicalAddress: 'Sagebrush Plains Sec 11, Elko, NV 89801',
    leadScore: 91,
    status: 'Not Interested',
    roadAccess: true,
    utilitiesNearby: false,
    notes: 'Seller returned postcard - marked as "not interested at current pricing metrics". Retrying later.',
    coords: { lat: 41.0504, lng: -115.3421 },
    appraiserRecordId: 'E-NV-ELK-5573022'
  },
  {
    id: 'prop-106',
    apn: '042-45-771F',
    county: 'Pasco',
    state: 'FL',
    city: 'Tampa',
    acreage: 2.1,
    zoning: 'Residential (Rural)',
    price: 52000,
    marketValue: 91000,
    ownerName: 'Arthur Dent',
    ownerPhone: '+1 (813) 555-4012',
    ownerMailAddress: '42 Galaxy Way, London, FL 32256',
    ownerPhysicalAddress: 'Saddlewood Estates Lot 8, Tampa, FL 33602',
    leadScore: 98,
    status: 'Approved',
    roadAccess: true,
    utilitiesNearby: true,
    notes: 'Extremely high demand high utility area with residential subdivisions adjacent.',
    coords: { lat: 27.9506, lng: -82.4572 },
    appraiserRecordId: 'P-FL-PAS-4245771'
  },
  {
    id: 'prop-107',
    apn: '901-82-351G',
    county: 'Dallas',
    state: 'TX',
    city: 'Dallas',
    acreage: 15.0,
    zoning: 'Commercial / Mixed Use',
    price: 110000,
    marketValue: 240000,
    ownerName: 'Texan Land Baron Trust',
    ownerPhone: '+1 (214) 555-7389',
    ownerMailAddress: '600 Lonestar Towers, Dallas, TX 75201',
    ownerPhysicalAddress: 'Frontage Sec 35 Interstate 35, Dallas, TX 75201',
    leadScore: 95,
    status: 'Sold',
    roadAccess: true,
    utilitiesNearby: true,
    notes: 'Wholesaled to institutional buyer in 3 days! Clean title, zero back taxes on file.',
    coords: { lat: 32.7767, lng: -96.7970 },
    appraiserRecordId: 'T-TX-DAL-9018235'
  },
  {
    id: 'prop-108',
    apn: '772-55-901H',
    county: 'Kern',
    state: 'CA',
    city: 'Bakersfield',
    acreage: 5.2,
    zoning: 'Open Range (Subdividable)',
    price: 18000,
    marketValue: 39000,
    ownerName: 'Bakersfield Holdings LLC',
    ownerPhone: '+1 (661) 555-3044',
    ownerMailAddress: '99 Palms Blvd, San Diego, CA 92109',
    ownerPhysicalAddress: 'Joshua Tree Flats Sec B, Bakersfield, CA 93301',
    leadScore: 87,
    status: 'Lead',
    roadAccess: true,
    utilitiesNearby: false,
    notes: 'Scenic solar panel-ready zone. Low property appraiser assessment makes holding cheap.',
    coords: { lat: 35.3733, lng: -119.0187 },
    appraiserRecordId: 'K-CA-KER-7725590'
  }
];

export const PLAN_COSTS = {
  'Starter': { monthly: 110, annual: 89 },
  'Pro': { monthly: 169, annual: 139 },
  'Pro Plus': { monthly: 269, annual: 223 }
};
